language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq python-dev libxslt1-dev libxml2-dev
install:
  - "cat requirements.txt | xargs -n1 conda install $1"
  - "cat requirements_test.txt | xargs -n1 conda install $1"
  - "conda list"
script: "nosetests --exclude=async"
notifications:
  email: false
